# typings/cep_py/__init__.pyi

from . import cep_py as cep_py

def build_entity_json(input_json: str) -> str: ...
def build_exchange_json(input_json: str) -> str: ...
def build_relationship_json(input_json: str) -> str: ...
def build_p3tag_json(input_json: str) -> str: ...
def generate_snfei(
    legal_name: str,
    country_code: str,
    address: str | None = ...,
    registration_date: str | None = ...,
) -> str: ...

__all__: list[str]
__doc__ = ...
if hasattr(cep_py, "__all__"): ...
