# typings/cep_py/__init__.pyi

from typing import Any

from . import cep_py as cep_py

def build_entity_json(input_json: str) -> str: ...
def build_exchange_json(input_json: str) -> str: ...
def build_relationship_json(input_json: str) -> str: ...
def build_ctag_json(input_json: str) -> str: ...
def generate_snfei(
    legal_name: str,
    country_code: str,
    address: str | None = ...,
    registration_date: str | None = ...,
) -> str: ...
def generate_snfei_detailed(
    legal_name: str,
    country_code: str,
    address: str | None = ...,
    registration_date: str | None = ...,
    lei: str | None = ...,
    sam_uei: str | None = ...,
) -> dict[str, Any]: ...
def normalize_legal_name_py(value: str) -> str: ...
def normalize_address_py(value: str) -> str: ...
def normalize_registration_date_py(value: str) -> str | None: ...

__all__: list[str]
__doc__ = ...
if hasattr(cep_py, "__all__"): ...
