//! CEP Core Library
//!
//! Provides foundational types and builders for:
//! - Entity
//! - Relationship
//! - Exchange
//! - P3Tag
//!
//! Also includes:
//! - Common ID types
//! - Attestation blocks
//! - Canonical timestamps
//! - JSON Schema registry (optional)
//!
//! All high-level domain modules follow this pattern:
//! - `generated.rs` (autogenerated from JSON Schema or codegen)
//! - `manual.rs` (handwritten logic, safe defaults, builder functions)
//!
//! Only the stable public API is re-exported here.

pub mod common;
pub mod entity;
pub mod relationship;
pub mod exchange;
pub mod p3tag;

// The Foreign Function Interface layer
pub mod ffi;
