// This file is auto-generated from JSON Schema.
// Do not edit this file by hand. Regenerate via the CLI.

#![allow(clippy::all)]
#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RecordKind {
    #[serde(rename = "entity")]
    Entity,
    #[serde(rename = "relationship")]
    Relationship,
    #[serde(rename = "exchange")]
    Exchange,
    #[serde(rename = "p3tag")]
    P3tag,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum StatusCode {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "INACTIVE")]
    Inactive,
    #[serde(rename = "DEPRECATED")]
    Deprecated,
    #[serde(rename = "PENDING")]
    Pending,
}

/// Lifecycle status of the record.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StatusEnvelope {
    #[serde(rename = "statusCode")]
    pub status_code: StatusCode,

    #[serde(rename = "statusReason")]
    pub status_reason: Option<String>,

    #[serde(rename = "statusEffectiveDate")]
    pub status_effective_date: String,
}

/// Shared timestamps for record lifecycle and validity.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Timestamps {
    #[serde(rename = "firstSeenAt")]
    pub first_seen_at: String,

    #[serde(rename = "lastUpdatedAt")]
    pub last_updated_at: String,

    #[serde(rename = "validFrom")]
    pub valid_from: String,

    #[serde(rename = "validTo")]
    pub valid_to: Option<String>,
}

/// Evidence about who asserted these facts and how.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Attestation {
    #[serde(rename = "attestationTimestamp")]
    pub attestation_timestamp: String,

    #[serde(rename = "attestorId")]
    pub attestor_id: String,

    #[serde(rename = "verificationMethodUri")]
    pub verification_method_uri: String,

    #[serde(rename = "proofType")]
    pub proof_type: String,

    #[serde(rename = "proofPurpose")]
    pub proof_purpose: String,

    #[serde(rename = "proofValue")]
    pub proof_value: Option<String>,

    #[serde(rename = "sourceSystem")]
    pub source_system: Option<String>,

    #[serde(rename = "sourceReference")]
    pub source_reference: Option<String>,
}

/// Defines a verifiable value exchange (financial, in-kind, or informational) between entities within an established relationship. This is the atomic unit of civic transparency. CEP Exchanges are designed to interoperate with Open Contracting Data Standard (OCDS) transactions, Schema.org MonetaryGrant/Payment, XBRL financial taxonomies, and campaign finance / education finance datasets via exchangeTypeUri, value, categorization, and sourceReferences.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExchangeRecord {
    #[serde(rename = "recordKind")]
    pub record_kind: RecordKind,

    #[serde(rename = "recordSchemaUri")]
    pub record_schema_uri: String,

    #[serde(rename = "schemaVersion")]
    pub schema_version: String,

    #[serde(rename = "revisionNumber")]
    pub revision_number: i64,

    #[serde(rename = "verifiableId")]
    pub verifiable_id: String,

    #[serde(rename = "recordTypeUri")]
    pub record_type_uri: String,

    pub status: StatusEnvelope,

    pub timestamps: Timestamps,

    pub attestations: Vec<Attestation>,

    pub ctags: Option<Vec<serde_json::Value>>,

    #[serde(rename = "relationshipId")]
    pub relationship_id: String,

    #[serde(rename = "exchangeTypeUri")]
    pub exchange_type_uri: String,

    #[serde(rename = "sourceEntity")]
    pub source_entity: serde_json::Value,

    #[serde(rename = "recipientEntity")]
    pub recipient_entity: serde_json::Value,

    pub value: serde_json::Value,

    #[serde(rename = "occurredTimestamp")]
    pub occurred_timestamp: String,

    #[serde(rename = "exchangeStatus")]
    pub exchange_status: serde_json::Value,

    #[serde(rename = "provenanceChain")]
    pub provenance_chain: Option<serde_json::Value>,

    pub categorization: Option<serde_json::Value>,

    #[serde(rename = "sourceReferences")]
    pub source_references: Option<Vec<serde_json::Value>>,

    pub attestation: Attestation,

    #[serde(rename = "previousRecordHash")]
    pub previous_record_hash: Option<String>,
}
